### ISSUE TITLE
minia without "-out" starts running then dies with HDF5 error

### ISSUE THREAD

**Issue by tseemann** [GATB/minia#1]
```
% minia -in SRR1661276_R1.fastq.gz -out-dir minia

HDF5-DIAG: Error detected in HDF5 (1.8.11) thread 0:
  #000: /builds/workspace/tool-minia-build-debian7-64bits-gcc-4.7/gatb-minia/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5F.c line 1500 in H5Fcreate(): unable to create file
    major: File accessibilty
    minor: Unable to open file
```

Does not do this if i add `-out` as well **BUT** then it doesn't put them in the `-out-dir` folder, but `.` instead.

This is the 2.0.7 binary.

**Comment by rchikhi** [comment]
Hi Torsten, I can reproduce the problem on the 2.0.7. It has been fixed in the current development code, hence the next release will have the fix. Thanks!
