### ISSUE TITLE
Can't locate the Minia-pipeline multi kmer script

### ISSUE THREAD

**Issue by tseemann** [GATB/minia#14]
From the manual:

_"For proper assembly, we rec- ommend that you use the Minia-pipeline that runs Minia multiple times, with an iterative multi-k algorithm.”_

Do you know where this script is?

**Comment by tseemann** [comment]
Can you add that link to the manual?

**Comment by rchikhi** [comment]
good idea

**Comment by rchikhi** [comment]
good idea
