### ISSUE TITLE
how to set sveral kmer

### ISSUE THREAD

**Issue by Shirley-Q** [GATB/minia#16]
Question1:
I use this command 'minia-v3.2.1-bin-Linux/bin/minia -in trim_cat.fq -kmer-size 101 -out-dir minia_assembly -max-memory 2048000' to assembly. But there was some error as followed in picture.
Question2:
I want to set kmer as 31,41,51,61, but the '-kmer-size 31,41,51,61' was not useful. could you help me? Thank you very much!

Best wishes,
Shirley

**Comment by Shirley-Q** [comment]
The error as followed
kmer 93
kmers 442777992 444055535
merge bubble 12314
contigs: 106363 n50: 8936 max: 654322 mean: 2839 total length: 301973682 n80: 2078
aligned 0 reads
confirmed bases: 0 correct reads: 0 bases: 0
distance mean -nan sd -nan
invalid insert distance
kmer 103
kmers 428402497 429376923
merge bubble 11583
contigs: 91483 n50: 10026 max: 654342 mean: 3294 total length: 301403122 n80: 2248
aligned 0 reads
confirmed bases: 0 correct reads: 0 bases: 0
distance mean -nan sd -nan
invalid insert distance
kmer 113
kmers 406322887 406985837
merge bubble 12358
contigs: 80380 n50: 11003 max: 654362 mean: 3741 total length: 300707459 n80: 2404
aligned 0 reads
confirmed bases: 0 correct reads: 0 bases: 0
distance mean -nan sd -nan
invalid insert distance
kmer 123
kmers 375362617 375725203
merge bubble 13540
contigs: 114273 n50: 9073 max: 701445 mean: 2702 total length: 308872731 n80: 2073
terminate called after throwing an instance of 'std::logic_error'
  what():  SequenceReader::SequenceReader() istream is invalid
Aborted (core dumped)

**Comment by rchikhi** [comment]
Hi Shirley, Minia alone cannot do multi-k, but we have a wrapper script that can do that: https://github.com/GATB/gatb-pipeline

**Comment by Shirley-Q** [comment]
Thank you very much!
But I have two questions:
The first:
I want to get only one assembly file. If i finish multi-kmer assembly, could the gatb-pipeline do it?
The second:
I use gatb-pipeline assembly. there were some error.could you help me? The error was as followed.
(2019-05-24 11:58:54) Execution of 'minia/minia' failed. Command line: 
     /home/yuke/gatb-minia-pipeline/tools/memused /home/yuke/gatb-minia-pipeline/minia/minia -in MUDIUN_cat_minia_k21-91_step10_assembly.list_reads -kmer-size 21 -abundance-min 2 -out MUDIUN_cat_minia_k21-91_step10_assembly_k21


Best wishes,
Shirley

**Comment by rchikhi** [comment]
Yes the final assembly file (assembly.fasta) or the last k value assembly (assembly_kXXX.fasta with higher value for XXX, typically 121 or 141) is the final assembly file. You can discard all other intermediate fasta files.
Regarding the error, could you tell me what's the full output of the following command?
 /home/yuke/gatb-minia-pipeline/minia/minia -in MUDIUN_cat_minia_k21-91_step10_assembly.list_reads -kmer-size 21 -abundance-min 2 -out MUDIUN_cat_minia_k21-91_step10_assembly_k21

Thanks.
Rayan
