### ISSUE TITLE
An error occurred while running

### ISSUE THREAD

**Issue by fengcong3** [GATB/minia#18]
But I know why

HDF5-DIAG: Error detected in HDF5 (1.8.18) thread 0:
#000: /software/minia-v3.2.1-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Dio.c line 173 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: /software/minia-v3.2.1-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Dio.c line 554 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: /software/minia-v3.2.1-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Dchunk.c line 1875 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: /software/minia-v3.2.1-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Dchunk.c line 2905 in H5D__chunk_lock(): data pipeline read failed
    major: Data filters
    minor: Filter operation failed
  #004: /software/minia-v3.2.1-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Z.c line 1372 in H5Z_pipeline(): filter returned failure during read
    major: Data filters
    minor: Read failed
  #005:/software/minia-v3.2.1-Source/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Zdeflate.c line 125 in H5Z_filter_deflate(): inflate() failed
    major: Data filters
    minor: Unable to initialize object

**Comment by rchikhi** [comment]
Do you know why?

**Comment by xiefumin1** [comment]
I think i know why,
the config may set like this:
1.fq.gz\r\n
2.fq.gz\r\n
but it should be like this；
1.fq.gz\n
2.fq.gz\n

**Comment by rchikhi** [comment]
ah nice, thanks!
