### ISSUE TITLE
What about Haplotype reconstruction and Minia

### ISSUE THREAD

**Issue by jblamyatifremer** [GATB/minia#19]
Hi Minia Creators, 

Did you have any idea/clues about the behaviour of Minia on a targeted genes with high ploidy samples (tumors) ?

best Regards,
JB

**Comment by rchikhi** [comment]
Hi, 
if you have high sequencing coverage / high read length, and make sure to use a high k value (or alternatively use https://github.com/GATB/gatb-minia-pipeline), then perhaps Minia can be able to reconstruct and separate haplotypes. The key is that the k-mer size needs to be longer than the longest region where no variant occurs between two haplotypes, and that this region needs to be spanned by sufficiently many error-free portions of reads. If this is not the case, then haplotypes will be reconstructed in separate contigs. It is possible to tune parameters to nudge Minia towards reconstructing a consensus sequence versus separating haplotypes but this is a bit advanced (the `-bulge-*` params for which there is no documentation) and not guaranteed to work, but if you would like to go this route, let me know. 
Rayan
