### ISSUE TITLE
Paired-end read support

### ISSUE THREAD

**Issue by mictadlo** [GATB/minia#2]
Hi, 
Any plans to implement paired-end read support? Have you ever tried  [Flash](http://scottmyourstone.blogspot.com.au/2013/10/merging-overlapping-paired-end-reads.html) or
shuffleReadsfasta.pl from Velvet?

Thank you in advance.

Mic

**Comment by tseemann** [comment]
@mictadlo `shuffleReads` just interleaves R1 and R2.  `FLASH` overlaps them into single end reads where possible.

**Comment by rchikhi** [comment]
Hi, indeed, as per the manual: "Giving paired or mate-pairs reads as input is OK, but keep in mind that Minia won't use pairing information. "
Pairing is used when scaffolding. You may use the following pipeline that combines Minia with the BESST scaffolder: https://github.com/GATB/gatb-minia-pipeline
