### ISSUE TITLE
-max-memory ignored

### ISSUE THREAD

**Issue by osowiecki** [GATB/minia#20]
In [DSK: Pass 1/1, Step 2: counting kmers ] the memory limit seems to be ignored. Minia went over the ram limit and entered SWAP.

**Comment by rchikhi** [comment]
by a lot?

**Comment by osowiecki** [comment]
Told it to use --max-memory 180000 and it used up 189G/189G (htop) and moved to swap. Can't tell how much swap it used as other applications filled up some swap previously. I assumed GATB is using Megabytes, not Mebibytes for this option.

free --mega 
              total        used        free      shared  buff/cache   available
Mem:         198027        2780         908           0      194338      19378

free --mebi
              total        used        free      shared  buff/cache   available
Mem:         193386        2716         900           0      189768      189246

**Comment by rchikhi** [comment]
I'd say it's a a bit risky to ask minia (or in fact, any big data program) to use close to the max memory of a system. If you you significantly lower it, all's fine?

**Comment by osowiecki** [comment]
Waiting for new results. Will edit this reply.
