### ISSUE TITLE
multiple input files

### ISSUE THREAD

**Issue by osowiecki** [GATB/minia#21]
Can I use multiple -1 -2 --mp-1 --mp-2 flags to load multiple input files or do I have to cat all files together (that's what I used previously). If they have to be concatenated, can both --mp-12 and -12 flags can be used at the same time?

../gatb-minia-pipeline/gatb --max-memory 150000 --nb-cores 38 \
--mp-1  /path/s-11kb_1_R1.fq.gz \
--mp-2  /path/s-11kb_1_R2.fq.gz \
--mp-1  /path/s-11kb_2_R1.fq.gz \
--mp-2  /path/s-11kb_2_R2.fq.gz \
--mp-1  /path/s-11kb_3_R1.fq.gz \
--mp-2  /path/s-11kb_3_R2.fq.gz \
--mp-1  /path/s-11kb_4_R1.fq.gz \
--mp-2  /path/s-11kb_4_R2.fq.gz \
--mp-1  /path/s-11kb_5_R1.fq.gz \
--mp-2  /path/s-11kb_5_R2.fq.gz \
--mp-1  /path/s-11kb_6_R1.fq.gz \
--mp-2  /path/s-11kb_6_R2.fq.gz \
--mp-1  /path/s-11kb_7_R1.fq.gz \
--mp-2  /path/s-11kb_7_R2.fq.gz \
--mp-1  /path/s-11kb_8_R1.fq.gz \
--mp-2  /path/s-11kb_8_R2.fq.gz \
-1  /path/s-400bp_1_R1.fq.gz \
-2  /path/s-400bp_1_R2.fq.gz \
-1  /path/s-400bp_2_R1.fq.gz \
-2  /path/s-400bp_2_R2.fq.gz \
-1  /path/s-400bp_3_R1.fq.gz \
-2  /path/s-400bp_3_R2.fq.gz \
-1  /path/s-400bp_4_R1.fq.gz \
-2  /path/s-400bp_4_R2.fq.gz \
-1  /path/s-400bp_5_R1.fq.gz \
-2  /path/s-400bp_5_R2.fq.gz \
-1  /path/s-400bp_6_R1.fq.gz \
-2  /path/s-400bp_6_R2.fq.gz \
-1  /path/s-400bp_7_R1.fq.gz \
-2  /path/s-400bp_7_R2.fq.gz \
-1  /path/s-400bp_8_R1.fq.gz \
-2  /path/s-400bp_8_R2.fq.gz \
-1  /path/s-500bp_1_R1.fq.gz \
-2  /path/s-500bp_1_R2.fq.gz \
-1  /path/s-500bp_2_R1.fq.gz \
-2  /path/s-500bp_2_R2.fq.gz \
-1  /path/s-500bp_3_R1.fq.gz \
-2  /path/s-500bp_3_R2.fq.gz \
-1  /path/s-500bp_4_R1.fq.gz \
-2  /path/s-500bp_4_R2.fq.gz \
-1  /path/s-500bp_5_R1.fq.gz \
-2  /path/s-500bp_5_R2.fq.gz \
-1  /path/s-500bp_6_R1.fq.gz \
-2  /path/s-500bp_6_R2.fq.gz \
-1  /path/s-500bp_7_R1.fq.gz \
-2  /path/s-500bp_7_R2.fq.gz \
-1  /path/s-500bp_8_R1.fq.gz \
-2  /path/s-500bp_8_R2.fq.gz \
--mp-1  /path/s-8kb_1_R1.fq.gz \
--mp-2  /path/s-8kb_1_R2.fq.gz \
--mp-1  /path/s-8kb_2_R1.fq.gz \
--mp-2  /path/s-8kb_2_R2.fq.gz \
--mp-1  /path/s-8kb_3_R1.fq.gz \
--mp-2  /path/s-8kb_3_R2.fq.gz \
--mp-1  /path/s-8kb_4_R1.fq.gz \
--mp-2  /path/s-8kb_4_R2.fq.gz \
--mp-1  /path/s-8kb_5_R1.fq.gz \
--mp-2  /path/s-8kb_5_R2.fq.gz \
--mp-1  /path/s-8kb_6_R1.fq.gz \
--mp-2  /path/s-8kb_6_R2.fq.gz \
--mp-1  /path/s-8kb_7_R1.fq.gz \
--mp-2  /path/s-8kb_7_R2.fq.gz \
--mp-1  /path/s-8kb_8_R1.fq.gz \
--mp-2  /path/s-8kb_8_R2.fq.gz

**Comment by rchikhi** [comment]
using multiple  -1's -2's, --mp-1's, --mp-2's is fine, no need to cat. And using both --12 and --mp-12 is also fine.
