### ISSUE TITLE
Log Message

### ISSUE THREAD

**Issue by heathheckman** [GATB/minia#24]
Hello - 
I am trying to troubleshoot a genome assembly, and in reading the minia log file I see several thousand instances of "Weird, there was supposed to be an in-neighbor. Maybe there's a loop. Remove this print if it never happensin degree 1" - does this have any impact on the output?  If so, how can I mitigate the issue?  Thank you.

**Comment by rchikhi** [comment]
Hi, is this with the latest Minia commit? These messages will have a minor impact, but should be considered as a debug message. I'd also recommend using gatb-pipeline if you're looking for a high contiguity assembly. (or test its competitors, Megahit and Spades)
