### ISSUE TITLE
minia generates non-deterministic assemblies?

### ISSUE THREAD

**Issue by morispi** [GATB/minia#25]
Hello,

I'm attempting to use minia to perform local assembly of Linked-Reads data, and realign the obtained contigs to determine breakpoints as a part of a SV calling tool.

However, when running multiple instances of minia, with the same parameters, and on the same input file, it seems to output (slightly) different assemblies.

While all assemblies are very similar, some of them sometimes end up messing up the breakpoints computation (although I can definitely take some of the blame on that problem).

I've tried playing around with the parameters a bit, but couldn't come up with something that would yield deterministic assemblies. So I'm wondering, is that an expected behaviour, or maybe am I overlooking something here?

Thanks.

Best,
Pierre

**Comment by rchikhi** [comment]
hi Pierre, I recall some simplifications operations are done in parallel, the best way to get deterministic results is therefore to use a single thread, hopefully your instance is small enough..

**Comment by morispi** [comment]
Hello Rayan,

Indeed, it seems like I missed the manual.tex information. :) Works well when using `-nb-cores 1 -nb-glue-partitions 200` as recommended. My instances are small enough, so this seems perfect.

Thanks a lot!
Pierre
