### ISSUE TITLE
Is 3.2.0 fast as before ?

### ISSUE THREAD

**Issue by DustinChen1986** [GATB/minia#9]
Minia old version is so fast and memory efficient. What about 3.2.0?

**Comment by rchikhi** [comment]
Still fast, not as memory-efficient (but still around an order of magnitude more memory efficient than other assemblers e.g. Megahit), much improved assembly quality.

**Comment by DustinChen1986** [comment]
We expect the paper and the mature version so much.

**Comment by rchikhi** [comment]
realistically and unfortunately, I don't see a short-read assembly paper being published anymore in this era of long-read assembly. But feel free to be in touch if you need to still perform short-read assembly
